#!/usr/bin/env bash
# ss13-db-backup
# use mysqldump to dump a SQL backup of the starfly13 database container

# dump the database to a compressed SQL file on standard out
MYSQL_ROOT_PASSWORD=$(head -1 config/dbconfig.txt | awk -e '{print $3}')
docker exec starfly_db \
	mysqldump --password=${MYSQL_ROOT_PASSWORD} starfly13 \
	| gzip -
