name: Build Windows
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:
    branches:
      - master

jobs:
  test_windows:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    name: "Build (Windows)"
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Build Project
        run: pwsh tools/starfly/ci/build.ps1
        env:
          DM_EXE: "C:\\byond\\bin\\dm.exe"
