name: Build Linux
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:
    branches:
      - master

jobs:
  build_linux:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    name: "Build (Linux)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install BYOND
        run: tools/starfly/ci/install_byond_linux.sh

      - name: Build Project
        run: |
          source ${HOME}/BYOND/byond/bin/byondsetup
          tools/build/build --ci dm -DCIBUILDING -DCITESTING -DALL_MAPS -DFULL_INIT
