name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    name: "Publish to GitHub Container Registry"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Enable Docker Cache
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('dependencies.sh') }}

    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Docker Meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/starfly-13/starfly-13
        # add git short SHA as Docker tag
        tags: |
          # branch event
          type=ref,event=branch
          # pull request event
          type=ref,event=pr
          # full length sha
          type=sha,format=long

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
