name: QA
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:
    branches:
      - master

jobs:
  check_file_dir:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    name: "Check (FILE_DIR)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Check FILE_DIR
        run: |
          count=$(grep -o 'FILE_DIR' shiptest.dme | wc -l)
          if [[ "$count" -ne 3 ]]; then
              echo "Error: shiptest.dme contains $count instances of FILE_DIR, expected exactly 3."
              echo "See: https://tgstation13.org/phpBB/viewtopic.php?f=5&t=321"
              exit 1
          fi
          echo "Success: shiptest.dme contains exactly 3 instances of FILE_DIR."
